const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const AUTH_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;

export {
  NOT_FOUND, BAD_REQUEST, SERVER_ERROR, AUTH_ERROR, CONFLICT_ERROR, FORBIDDEN_ERROR,
};
